USE AdventureWorks2012;
GO
BEGIN TRY
	SELECT 217/0;
END TRY
BEGIN CATCH
SELECT
ERROR_NUMBER () AS ErrorNumber,
ERROR_SEVERITY () AS ErrorSeverity,
ERROR_LINE () AS ErrorLine,
ERROR_MESSAGE () AS ErrorMessage;
END CATCH;
GO